import type {Env} from "../types";
import {getActions,getBusiness,getCatalogView,getPolicies} from "./service";

// A hosted agents.md for a connected business, generated from the SAME service functions the JSON
// and MCP surfaces use. There is deliberately no second source of truth, so this file cannot drift
// from what the API says -- and it inherits the same guarantee that only public, merchant-approved
// fields are ever emitted.

const esc=(v:unknown)=>String(v==null?"":v).replace(/[\r\n]+/g," ").trim();

export async function buildAgentsMd(env:Env,shop:string,slug:string,appUrl:string){
  const [business,catalog,policies,actions]=await Promise.all([
    getBusiness(env,shop,slug),getCatalogView(env,shop,25),getPolicies(env,shop),getActions(env,shop)
  ]);
  if(!business)return null;

  const base=`${appUrl.replace(/\/$/,"")}/api/ai/${slug}`;
  const lines:string[]=[];

  lines.push(`# ${esc(business.name)||slug}`,"");
  if(business.description)lines.push(esc(business.description),"");
  lines.push("This file describes how an AI agent can understand and act with this business.",
    "It is generated by AgentCart from data the merchant has connected and approved.","");

  lines.push("## Business","");
  if(business.website)lines.push(`- Website: ${esc(business.website)}`);
  if(business.contact?.email)lines.push(`- Email: ${esc(business.contact.email)}`);
  if(business.contact?.phone)lines.push(`- Phone: ${esc(business.contact.phone)}`);
  const where=[business.location?.city,business.location?.region,business.location?.country].filter(Boolean).join(", ");
  if(where)lines.push(`- Location: ${esc(where)}`);
  if(business.currency)lines.push(`- Currency: ${esc(business.currency)}`);
  lines.push(`- Last updated: ${esc(business.lastUpdated)}`,"");

  lines.push("## Machine-readable endpoints","",
    "Prefer these over parsing this file or scraping the website.","",
    `- Business profile: ${base}/profile`,
    `- Catalogue: ${base}/catalog`,
    `- Item detail: ${base}/items/{id-or-handle}`,
    `- Search: ${base}/search?q={query}`,
    `- Policies: ${base}/policies`,
    `- Supported actions: ${base}/actions`,
    `- MCP (read-only, JSON-RPC over POST): ${base}/mcp`,"");

  lines.push("## What you can and cannot do","");
  for(const a of actions)
    lines.push(`- **${a.supported?"Supported":"Not supported"}** — ${esc(a.description)}`
      +(a.url?` (${esc(a.url)})`:"")
      +(a.limitations?` _${esc(a.limitations)}_`:""));
  lines.push("");

  if(policies.length){
    lines.push("## Policies","");
    for(const p of policies)lines.push(`- ${esc(p.title)}: ${esc(p.url)}`);
    lines.push("");
  }

  if(catalog.length){
    lines.push("## Catalogue sample","",
      `Showing ${catalog.length} item(s). Use the catalogue endpoint above for the full list.`,"",
      "| Item | Price | In stock |","| --- | --- | --- |");
    for(const i of catalog)
      lines.push(`| ${esc(i.title)} | ${i.price.min!=null?`${esc(i.price.currency)} ${i.price.min}`:"—"} | ${i.available?"Yes":"No"} |`);
    lines.push("");
  }

  lines.push("## Provenance","",
    "Synced from the merchant's connected store. This file contains only public or",
    "merchant-approved information. It never contains credentials, customer data or internal analytics.","");

  return lines.join("\n");
}
